version: "3.3"
services:
  registry:
    image: registry:latest
    container_name: registry-by-mqz
    #environment:
    #  - I18N_LOCALE=zh-CN
    ports:
      - "5040:5000"
    volumes:
      - /root/mqz/docker-registry/docker-dir:/var/lib/registry
    #networks:
    #  - kibana
    privileged: true
#networks:
#  kibana:
#    driver: bridge
